import { join } from "node:path";
import type { BbgConfig, RepoEntry, RepoType } from "../config/schema.js";
import { CLI_VERSION, DEFAULT_STACK, REPO_TYPE_CHOICES } from "../constants.js";
import { analyzeRepo } from "../analyzers/index.js";
import { ensureGitAvailable, listRemoteBranches, cloneRepo } from "../utils/git.js";
import { collectStackInfo, sanitizePromptValue, promptConfirm, promptInput, promptSelect } from "../utils/prompts.js";
import { inferRepoName, isParseableGitUrl } from "../utils/git-url.js";

/* ------------------------------------------------------------------ */
/*  Options accepted by collectInitConfig                              */
/* ------------------------------------------------------------------ */

interface CollectInitOptions {
  cwd: string;
  yes?: boolean;
  dryRun?: boolean;
}

/* ------------------------------------------------------------------ */
/*  Baseline config builder                                            */
/* ------------------------------------------------------------------ */

function buildBaselineConfig(nowIso: string): BbgConfig {
  return {
    version: CLI_VERSION,
    projectName: "bbg-project",
    projectDescription: "Generated by bbg init",
    createdAt: nowIso,
    updatedAt: nowIso,
    repos: [],
    governance: {
      riskThresholds: {
        high: { grade: "A+", minScore: 99 },
        medium: { grade: "A", minScore: 95 },
        low: { grade: "B", minScore: 85 },
      },
      enableRedTeam: true,
      enableCrossAudit: true,
    },
    context: {},
  };
}

/* ------------------------------------------------------------------ */
/*  Risk threshold parsing                                             */
/* ------------------------------------------------------------------ */

function parseRiskThresholdInput(
  raw: string,
  fallback: { grade: string; minScore: number },
): { grade: string; minScore: number } {
  const parts = raw.split(":").map((part) => part.trim());
  if (parts.length !== 2 || parts[0]?.length === 0) {
    return fallback;
  }

  const score = Number(parts[1]);
  if (!Number.isFinite(score)) {
    return fallback;
  }

  return {
    grade: parts[0],
    minScore: score,
  };
}

/* ------------------------------------------------------------------ */
/*  Interactive config collection                                      */
/* ------------------------------------------------------------------ */

export interface InitCollectionResult {
  config: BbgConfig;
  clonedRepos: string[];
}

export async function collectInitConfig(nowIso: string, options: CollectInitOptions): Promise<InitCollectionResult> {
  const defaults = buildBaselineConfig(nowIso);
  if (options.yes) {
    return {
      config: defaults,
      clonedRepos: [],
    };
  }

  await ensureGitAvailable();

  const projectName = sanitizePromptValue(
    await promptInput({ message: "Project name", default: defaults.projectName }),
    defaults.projectName,
  );
  const projectDescription = sanitizePromptValue(
    await promptInput({ message: "Project description", default: defaults.projectDescription }),
    defaults.projectDescription,
  );

  const repos: RepoEntry[] = [];
  const clonedRepos: string[] = [];
  let shouldAddRepo = await promptConfirm({ message: "Add repository now?", default: true });

  while (shouldAddRepo) {
    const gitUrl = sanitizePromptValue(
      await promptInput({ message: "Repository git URL" }),
      "",
    );
    if (!isParseableGitUrl(gitUrl)) {
      throw new Error("Repository git URL is invalid. Please provide a parseable git URL.");
    }
    const { branches: remoteBranches, credentials } = await listRemoteBranches(gitUrl);
    const branchChoices = (remoteBranches.length > 0 ? remoteBranches : ["main"]).map((branch: string) => ({
      name: branch,
      value: branch,
    }));
    const branch = await promptSelect<string>({
      message: "Select default branch",
      choices: branchChoices,
      default: branchChoices[0]?.value,
    });
    const repoName = inferRepoName(gitUrl);
    const targetDir = join(options.cwd, repoName);

    let stack = DEFAULT_STACK;
    if (!options.dryRun) {
      await cloneRepo({ url: gitUrl, branch, targetDir, credentials: credentials ?? undefined });
      clonedRepos.push(targetDir);
      const analysis = await analyzeRepo(targetDir);
      stack = await collectStackInfo(analysis.stack);
    }

    const type = await promptSelect<RepoType>({
      message: "Repository type",
      choices: REPO_TYPE_CHOICES,
      default: "other",
    });
    const description = sanitizePromptValue(
      await promptInput({ message: "Repository description", default: "" }),
      "",
    );

    repos.push({
      name: repoName,
      gitUrl,
      branch,
      type,
      stack,
      description,
    });

    shouldAddRepo = await promptConfirm({ message: "Add another repository?", default: false });
  }

  const overrideThresholds = await promptConfirm({
    message: "Override default governance risk thresholds?",
    default: false,
  });

  const riskThresholds = overrideThresholds
    ? {
        high: parseRiskThresholdInput(
          await promptInput({ message: "High risk threshold (GRADE:score)", default: "A+:99" }),
          defaults.governance.riskThresholds.high,
        ),
        medium: parseRiskThresholdInput(
          await promptInput({ message: "Medium risk threshold (GRADE:score)", default: "A:95" }),
          defaults.governance.riskThresholds.medium,
        ),
        low: parseRiskThresholdInput(
          await promptInput({ message: "Low risk threshold (GRADE:score)", default: "B:85" }),
          defaults.governance.riskThresholds.low,
        ),
      }
    : defaults.governance.riskThresholds;

  const enableRedTeam = await promptConfirm({
    message: "Enable red-team workflow?",
    default: defaults.governance.enableRedTeam,
  });
  const enableCrossAudit = await promptConfirm({
    message: "Enable cross-audit workflow?",
    default: defaults.governance.enableCrossAudit,
  });

  return {
    config: {
      ...defaults,
      projectName,
      projectDescription,
      repos,
      governance: {
        riskThresholds,
        enableRedTeam,
        enableCrossAudit,
      },
    },
    clonedRepos,
  };
}
