import { join } from "node:path";
import type { BbgConfig, RepoEntry, RepoType } from "../config/schema.js";
import { inferDocumentationLanguageFromEnv } from "../config/documentation-language.js";
import { CLI_VERSION, DEFAULT_STACK, REPO_TYPE_CHOICES } from "../constants.js";
import { analyzeRepo } from "../analyzers/index.js";
import { buildDefaultRuntimeConfig } from "../runtime/schema.js";
import { uiText } from "../i18n/ui-copy.js";
import {
  cloneRepo,
  discoverLocalChildRepos,
  ensureGitAvailable,
  listRemoteBranches,
} from "../utils/git.js";
import { collectStackInfo, sanitizePromptValue, promptConfirm, promptInput, promptSelect } from "../utils/prompts.js";
import { inferRepoName, isParseableGitUrl } from "../utils/git-url.js";
import { applyPreservedInitInfo, INIT_INFO_CACHE_PATH, type PreservedInitInfo } from "./init-info-cache.js";

/* ------------------------------------------------------------------ */
/*  Options accepted by collectInitConfig                              */
/* ------------------------------------------------------------------ */

interface CollectInitOptions {
  cwd: string;
  yes?: boolean;
  dryRun?: boolean;
  initInfo?: PreservedInitInfo | null;
}

/* ------------------------------------------------------------------ */
/*  Baseline config builder                                            */
/* ------------------------------------------------------------------ */

function buildBaselineConfig(nowIso: string): BbgConfig {
  return {
    version: CLI_VERSION,
    projectName: "bbg-project",
    projectDescription: "Generated by bbg init",
    documentationLanguage: inferDocumentationLanguageFromEnv(),
    createdAt: nowIso,
    updatedAt: nowIso,
    repos: [],
    governance: {
      riskThresholds: {
        high: { grade: "A+", minScore: 99 },
        medium: { grade: "A", minScore: 95 },
        low: { grade: "B", minScore: 85 },
      },
      enableRedTeam: true,
      enableCrossAudit: true,
    },
    context: {},
    runtime: buildDefaultRuntimeConfig(),
  };
}

/* ------------------------------------------------------------------ */
/*  Risk threshold parsing                                             */
/* ------------------------------------------------------------------ */

function parseRiskThresholdInput(
  raw: string,
  fallback: { grade: string; minScore: number },
): { grade: string; minScore: number } {
  const parts = raw.split(":").map((part) => part.trim());
  if (parts.length !== 2 || parts[0]?.length === 0) {
    return fallback;
  }

  const score = Number(parts[1]);
  if (!Number.isFinite(score)) {
    return fallback;
  }

  return {
    grade: parts[0],
    minScore: score,
  };
}

/* ------------------------------------------------------------------ */
/*  Interactive config collection                                      */
/* ------------------------------------------------------------------ */

export interface InitCollectionResult {
  config: BbgConfig;
  clonedRepos: string[];
}

export async function collectInitConfig(nowIso: string, options: CollectInitOptions): Promise<InitCollectionResult> {
  const baselineDefaults = buildBaselineConfig(nowIso);
  const preservedDefaults = applyPreservedInitInfo(baselineDefaults, options.initInfo ?? null);
  if (options.yes) {
    return {
      config: preservedDefaults,
      clonedRepos: [],
    };
  }

  await ensureGitAvailable();

  if (options.initInfo) {
    const usePreservedInfo = await promptConfirm({
      message: uiText("init.usePreservedInitInfo", { value: INIT_INFO_CACHE_PATH }),
      default: true,
    });

    if (usePreservedInfo) {
      return {
        config: preservedDefaults,
        clonedRepos: [],
      };
    }
  }

  const projectName = sanitizePromptValue(
    await promptInput({ message: uiText("init.projectName"), default: baselineDefaults.projectName }),
    baselineDefaults.projectName,
  );
  const projectDescription = sanitizePromptValue(
    await promptInput({ message: uiText("init.projectDescription"), default: baselineDefaults.projectDescription }),
    baselineDefaults.projectDescription,
  );

  const repos: RepoEntry[] = [];
  const clonedRepos: string[] = [];
  const detectedLocalRepos = await discoverLocalChildRepos(options.cwd);

  for (const localRepo of detectedLocalRepos) {
    const shouldAddDetectedRepo = await promptConfirm({
      message: uiText("init.addDetectedLocalRepository", { value: localRepo.relativePath }),
      default: true,
    });
    if (!shouldAddDetectedRepo) {
      continue;
    }

    const analysis = await analyzeRepo(localRepo.absolutePath);
    const stack = await collectStackInfo(analysis.stack);
    const type = await promptSelect<RepoType>({
      message: uiText("init.repositoryType"),
      choices: REPO_TYPE_CHOICES,
      default: "other",
    });
    const description = sanitizePromptValue(
      await promptInput({ message: uiText("init.repositoryDescription"), default: "" }),
      "",
    );

    repos.push({
      name: localRepo.name,
      gitUrl: localRepo.remoteUrl,
      branch: localRepo.branch,
      type,
      stack,
      description,
    });
  }

  let shouldAddRepo = await promptConfirm({
    message: uiText("init.addRepositoryNow"),
    default: detectedLocalRepos.length === 0,
  });

  while (shouldAddRepo) {
    const gitUrl = sanitizePromptValue(
      await promptInput({ message: uiText("init.repositoryGitUrl") }),
      "",
    );
    if (!isParseableGitUrl(gitUrl)) {
      throw new Error("Repository git URL is invalid. Please provide a parseable git URL.");
    }
    const { branches: remoteBranches, credentials } = await listRemoteBranches(gitUrl);
    const branchChoices = (remoteBranches.length > 0 ? remoteBranches : ["main"]).map((branch: string) => ({
      name: branch,
      value: branch,
    }));
    const branch = await promptSelect<string>({
      message: uiText("init.selectDefaultBranch"),
      choices: branchChoices,
      default: branchChoices[0]?.value,
    });
    const repoName = inferRepoName(gitUrl);
    const targetDir = join(options.cwd, repoName);

    let stack = DEFAULT_STACK;
    if (!options.dryRun) {
      await cloneRepo({ url: gitUrl, branch, targetDir, credentials: credentials ?? undefined });
      clonedRepos.push(targetDir);
      const analysis = await analyzeRepo(targetDir);
      stack = await collectStackInfo(analysis.stack);
    }

    const type = await promptSelect<RepoType>({
      message: uiText("init.repositoryType"),
      choices: REPO_TYPE_CHOICES,
      default: "other",
    });
    const description = sanitizePromptValue(
      await promptInput({ message: uiText("init.repositoryDescription"), default: "" }),
      "",
    );

    repos.push({
      name: repoName,
      gitUrl,
      branch,
      type,
      stack,
      description,
    });

    shouldAddRepo = await promptConfirm({ message: uiText("init.addAnotherRepository"), default: false });
  }

  const overrideThresholds = await promptConfirm({
    message: uiText("init.overrideRiskThresholds"),
    default: false,
  });

  const riskThresholds = overrideThresholds
    ? {
        high: parseRiskThresholdInput(
          await promptInput({ message: uiText("init.highRiskThreshold"), default: "A+:99" }),
          baselineDefaults.governance.riskThresholds.high,
        ),
        medium: parseRiskThresholdInput(
          await promptInput({ message: uiText("init.mediumRiskThreshold"), default: "A:95" }),
          baselineDefaults.governance.riskThresholds.medium,
        ),
        low: parseRiskThresholdInput(
          await promptInput({ message: uiText("init.lowRiskThreshold"), default: "B:85" }),
          baselineDefaults.governance.riskThresholds.low,
        ),
      }
    : baselineDefaults.governance.riskThresholds;

  const enableRedTeam = await promptConfirm({
    message: uiText("init.enableRedTeam"),
    default: baselineDefaults.governance.enableRedTeam,
  });
  const enableCrossAudit = await promptConfirm({
    message: uiText("init.enableCrossAudit"),
    default: baselineDefaults.governance.enableCrossAudit,
  });

  return {
    config: {
      ...baselineDefaults,
      projectName,
      projectDescription,
      repos,
      governance: {
        riskThresholds,
        enableRedTeam,
        enableCrossAudit,
      },
    },
    clonedRepos,
  };
}
