import { basename, join } from "node:path";
import { parseConfig } from "../config/read-write.js";
import { exists, readTextFile, writeTextFile } from "../utils/fs.js";

export interface RunTaskStartCommandInput {
  cwd: string;
  requirement?: string;
  file?: string;
  workflow?: string;
  profile?: "quick" | "standard" | "deep";
  autoWiki?: boolean;
}

export interface RunTaskStartCommandResult {
  taskId: string;
  workflow: string;
  specPath: string;
  wikiPath: string | null;
}

interface TaskIndexEntry {
  taskId: string;
  slug: string;
  specPath: string;
  createdAt: string;
}

function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || "task"
  );
}

function datedPath(prefix: string, slug: string, suffix = ""): string {
  const now = new Date();
  const y = String(now.getUTCFullYear());
  const m = String(now.getUTCMonth() + 1).padStart(2, "0");
  return `${prefix}/${y}/${m}/${slug}${suffix}`;
}

async function readTaskIndex(pathValue: string): Promise<TaskIndexEntry[]> {
  if (!(await exists(pathValue))) {
    return [];
  }
  const parsed = JSON.parse(await readTextFile(pathValue)) as { tasks?: TaskIndexEntry[] };
  return Array.isArray(parsed.tasks) ? parsed.tasks : [];
}

export async function runTaskStartCommand(input: RunTaskStartCommandInput): Promise<RunTaskStartCommandResult> {
  const configPath = join(input.cwd, ".bbg", "config.json");
  if (!(await exists(configPath))) {
    throw new Error(".bbg/config.json not found. Run `bbg init` first.");
  }
  parseConfig(await readTextFile(configPath));

  const fromFile = input.file ? await readTextFile(join(input.cwd, input.file)) : "";
  const requirementRaw = (input.requirement ?? fromFile).trim();
  if (requirementRaw.length === 0) {
    throw new Error("task-start requires requirement text or --file.");
  }

  const slug = slugify(requirementRaw.split(/\r?\n/)[0] ?? "task");
  const now = new Date().toISOString();
  const taskId = `TASK-${now.slice(0, 10).replaceAll("-", "")}-${now.slice(11, 19).replaceAll(":", "")}`;
  const specPath = datedPath("docs/specs", slug, ".md");
  const workflow = input.workflow ?? "full-feature";
  const profile = input.profile ?? "standard";

  const specContent = [
    "# Confirmed Requirement",
    "",
    `- Task ID: ${taskId}`,
    `- Created At: ${now}`,
    `- Interview Profile: ${profile}`,
    `- Workflow: ${workflow}`,
    "- Status: confirmed",
    "",
    "## Requirement",
    "",
    requirementRaw,
    "",
    "## Notes",
    "",
    "- Generated by `bbg task-start`.",
    "- This artifact is intended as the confirmed pre-execution requirement.",
    "",
  ].join("\n");
  await writeTextFile(join(input.cwd, specPath), specContent);

  let wikiPath: string | null = null;
  if (input.autoWiki ?? true) {
    wikiPath = `docs/wiki/concepts/${slug}.md`;
    const wikiContent = [
      "# Requirement Knowledge",
      "",
      `- Source spec: ${specPath}`,
      `- Task ID: ${taskId}`,
      `- Updated At: ${now}`,
      "",
      "## Summary",
      "",
      requirementRaw,
      "",
    ].join("\n");
    await writeTextFile(join(input.cwd, wikiPath), wikiContent);
  }

  const indexPath = join(input.cwd, ".bbg", "tasks", "index.json");
  const tasks = await readTaskIndex(indexPath);
  tasks.push({ taskId, slug, specPath, createdAt: now });
  await writeTextFile(indexPath, `${JSON.stringify({ version: 1, tasks }, null, 2)}\n`);

  const specsIndexPath = join(input.cwd, "docs", "specs", "index.md");
  const specsIndex = (await exists(specsIndexPath))
    ? await readTextFile(specsIndexPath)
    : "# Specs Index\n\n| Date | Task ID | Spec |\n| --- | --- | --- |\n";
  const specsRow = `| ${now.slice(0, 10)} | ${taskId} | [${basename(specPath)}](${specPath.replace("docs/specs/", "")}) |`;
  await writeTextFile(specsIndexPath, `${specsIndex.trimEnd()}\n${specsRow}\n`);

  return { taskId, workflow, specPath, wikiPath };
}
